Repository Keerat666/LeetCode-HacktoberFest22, pull requests merged in 2022-10, with the labels that each got.

#5 Create Solution.cpp #3
  Leetcode-Easy/Solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#8 Fixes issue #2: added solution for two sums problem in python
  Leetcode-Easy/1-TwoSum/Solution.py
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#11 added solution for Hard 135-Candy
  Leetcode-Hard/135-Candy/Solution.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Hard

#13 Add Q-26 RemoveDuplicatesFromSortedArray
  Leetcode-Easy/26-RemoveDuplicatesFromSortedArray/26_RemoveDuplicatesFromSortedArray.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#15 Added solution in C++
  Leetcode-Hard/135-Candy/solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Hard

#12 added some changes in palindrome
  Leetcode-Easy/9-PalindromeNumber/Solution.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#24 Folder created and added the solution in it
  14-LongestCommonPrefix/longest_common_prefix.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#25 Create 27. Remove Elements.cpp
  Leetcode-Easy/27. Remove Elements.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#26 Added C++ solution for the Climbing Stairs problem (issue #19)
  Leetcode-Easy/70-ClimbingStairs/Solution.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#28 Create 4-Median of Two Sorted Arrays
  Leetcode-Hard/4-Median of Two Sorted Arrays
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Hard

#29 Added solution for 3sum
  Leetcode-Medium/15-3Sum/3Sum.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Medium

#32 solved issue #27 : 31. Next Permutation cpp code
  Leetcode-Medium/31-NextPermutation/solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Medium

#33 Create Create 21. Merge two sorted lists in C.cpp
  Create 21. Merge two sorted lists in C.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#42 Added solution
  Leetcode-Easy/58-LengthOfLastWord/Solution.java
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#41 Added C++ solution for the Single Number leetcode problem (issue #20)
  Leetcode-Easy/136-SingleNumber/Solution.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#40 Added code to determine length of the last word
  lastword.java
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#48 Add solution for 518. Coin Change II (Issue #36)
  Leetcode-Medium/518-CoinChangeII/Coin-Change-II.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Medium

#45 solved issue #37 : 1482. Minimum Number of Days to Make m Bouquets cpp code
  Leetcode-Medium/1482-Minimum Number of Days to Make m Bouquets/solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Medium

#49 Python solution for Palindrome Number added
  Leetcode-Easy/9-PalindromeNumber/Solution.py
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#47 removing duplicates from an array using c++
  Leetcode-Easy/26-RemoveDuplicatesFromSortedArray/26-RemoveDuplicatesFromSortedArrayincpp.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#46 added python solution
  Leetcode-Easy/58-LengthOfLastWord/solution.py
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#53 Create singlenumber.cpp
  Leetcode-Easy/136-SingleNumber/singlenumber.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#55 Create singlenumber.py
  Leetcode-Easy/136-SingleNumber/singlenumber.py
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#58 Added code for trapping rain water
  Leetcode-Hard/42-TrappingRainWater/trapping_rain_water.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Hard

#61 Create romanToInteger.cpp
  Leetcode-Easy/13-RomanToInteger/romanToInteger.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#62 added python solution
  Leetcode-Easy/26-RemoveDuplicatesFromSortedArray/RemoveDuplicatesFromSortedArray.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#60 Create twosum.cpp
  Leetcode-Easy/1-TwoSum/twosum.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#74 Max Consecutive Ones Problem's Solution
  Leetcode-Easy/485-MaxConsecutiveOnes/MaxConsecutiveOnes.java
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#73 create palindrome number
  Leetcode-Easy/9-PalindromeNumber/palindromesolution1.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#72 Fix Issue #70: Longest Increasing Path in a Matrix Python
  Leetcode-Hard/329-LongestIncreasingPathInMatrix/Solution.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Hard

#69 136-SingleNumber Solved
  Leetcode-Easy/136-SingleNumber/singlenumbersolution.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#67 Created Solution.c for 58-LengthofLastWord
  Leetcode-Easy/58-LengthofLastWord/Solution.c
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#22 Create 35. Search Insert Position.cpp
  Leetcode-Easy/35-SearchInsertPosition/35. Search Insert Position.py
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#76 reshape the matrix
  Leetcode-Easy/566.Reshape the matrix/reshape_the_matrix.java
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#64 Create find_minimum_in_rotated_sorted_array_ii.cpp
  Leetcode-Hard/Find Minimum in Rotated Sorted Array II C++/find_minimum_in_rotated_sorted_array_ii.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Hard

#82 1578- Minimum Time to Make Rope Colorful
  Leetcode-Medium/1578- Minimum Time to Make Rope Colorful/1578. Minimum Time to Make Rope Colorful.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Medium

#63 Create Soution.java
  Leetcode-Medium/148 - Kth Largest Element in an Array/Soution.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Medium

#94 Palindrome Program in Java
  Leetcode-Easy/9-PalindromeNumber/javasolution.java
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#92 added JS solution to 4-median of 2 sorted arrays
  Leetcode-Easy/13-RomanToInteger/Solution.js
  Leetcode-Hard/4-MedianOfTwoSortedArrays/Solution.js
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#66 added kth Smallest Element in a Sorted Matrix
  .vscode/c_cpp_properties.json
  Leetcode-Medium/230-kth SmallestinBST/solution.py
  Leetcode-Medium/378-kth_Smallest_Element/solve.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#38 14. Longest Common Prefix
  Leetcode-Easy/14-LongestCommonPrefix/Longest_Common_Prefix.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#39 Added code for palindrome Number
  Leetcode-Easy/9-Palindrome.java
  Palindrome.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#54 Create 14. Longest Common Prefix
  Leetcode-Easy/14. Longest Common Prefix
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Easy

#75 Added Solution
  Leetcode-Easy/Best Time to Buy and Sell Stock
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#80 Added solution for 1578.Minimum Time to make rope colorful
  Leetcode-Medium/1578 - Minimum time to make rope colorful/code.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#103 solved #57
  Leetcode-Easy/Search Insert Position/searchInsertPosition.cpp
  Leetcode-Medium/3sum/3sum.cpp
  Leetcode-Medium/Find Minimum in Rotated Sorted Array II./ Find Minimum in Rotated Sorted Array II.cpp
  Leetcode-Medium/Partitioning Into Minimum Number Of Deci-Binary Numbers/Partitioning Into Minimum Number Of Deci-Binary Numbers.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#136 solution to reverse_integer problem in java
  Leetcode-Medium/7-Reverse Integer/reverse-integer.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#135 Update solution of median of two sorted array
  Leetcode-Hard/4-MedianOfTwoSortedArrays/solution.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#133 Create 16-3SumClosest
  Leetcode-Medium/16-3SumClosest
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#123 TwoSum Java
  Leetcode-Easy/1-TwoSum/Solution.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#134 add solution for 941. Valid Mountain Array in cpp
  Leetcode-Easy/941-ValidMountainArray/solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#130 add solution for 946. Validate Stack Sequences in cpp
  Leetcode-Medium/946-validate-stack-sequences/solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#128 add solution for 98. Validate Binary Search Tree in cpp
  Leetcode-Medium/98-ValidateBinarySearchTree/solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#126 add solution for 5. Longest Palindromic Substring in cpp
  Leetcode-Medium/5-LongestPalindromicSubstring/solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#122 Solved Max Consecutive Ones in C++
  Leetcode-Easy/485-MaxConsecutiveOnes/MaxConsecutiveOnes.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#121 add solution for 3 - Longest Substring Without repeating characters i…
  Leetcode-Medium/3-LongestSubstringWithoutRepeatingCharacters/Solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#120 Added CPP solution to HARD LeetCode question 51. N-Queens
  Leetcode-Hard/51. N-Queens/N-Queens.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#117 Add solution for Leetcode problem 123. (Issue #43)
  Leetcode-Hard/123-BestTimeToBuyAndSellStockIII/Best-Time-to-Buy-and-Sell-Stock-III.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#114 Added 2 solutions using partitioning and min heap
  Leetcode-Medium/148 - Kth Largest Element in an Array/C++/Solution_Using_Partitioning.cpp
  Leetcode-Medium/148 - Kth Largest Element in an Array/C++/Solution_Using_Priority_Queue.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#113 word-break-ii Leetcode java solution
  Leetcode-Hard/140-WordBreak-II/Word_Break_II.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#112 Added 1689-PartitioningIntoMinNoOfDeci-BinNos problem
  Leetcode-Medium/1689-PartitioningIntoMinNumOfDeci-BinaryNos/Solution.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#107 adding code for N-Queen ll
  Leetcode-Hard/52-N-Queens ll/solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, Leetcode-Hard

#101 Create 140. Word Break.cpp
  Leetcode-Hard/140-Word Break ll/Word_Break_ll.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#87 added longest-increasing-path-in-matrix in python
  Leetcode-Hard/329-LongestIncreasingPathInMatrix/longest-increasing-path-in-matrix.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#86 Time based
  Leetcode-Medium/623- Add One Row to Tree/623. Add One Row to Tree.cpp
  Leetcode-Medium/981. Time Based Key-Value Store/981. Time Based Key-Value Store.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#85 Added Code for Largest Rectangle in Histogram
  Leetcode-Hard/84-LargestRectangleInHistogram/LargestRectangleInHistogram.cpp
  Leetcode-Hard/84-LargestRectangleInHistogram/solution.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#178 solution in different way c++.
  Leetcode-Medium/7-Reverse Integer/new_solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#177 solution to N-Queens II problem in java
  Leetcode-Hard/52-N-Queens ll/N-Queens II.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#173 2365 Task-scheduler-II
  Leetcode-Medium/2365-Task-scheduler-ii/2365-Task-scheduler-ii.cpp
  Leetcode-Medium/2365-Task-scheduler-ii/README.MD
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#168 Leetcode Solution in CPP
  Leetcode-Easy/653. Two Sum IV - Input is a BST/Two Sum IV - Input is a BST.cpp
  Leetcode-Medium/1328. Break a Palindrome/Break_a_Palindrome.cpp
  Leetcode-Medium/334. Increasing Triplet Subsequence/Increasing Triplet Subsequence
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#166 Added solution for 199. Binary tree right side view
  Leetcode-Medium/199. Binary Tree Right Side View/199. Binary Tree Right Side View.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#165 reverse integer
  Leetcode-Medium/7-Reverse Integer/reverseinteger.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#163 search insert postions
  Leetcode-Easy/Search Insert Position/search_insert_position.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#158 Problem 199-BinaryTreeRightSideView solved
  Leetcode-Medium/199. Binary Tree Right Side View/199-BinaryTreeRightSideView.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#153 Added Spiral Matrix code
  Leetcode-Medium/54. Spiral Matrix/Spiral Matrix.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#152 22 generate parentheses solution added, PR under hacktoberfest 2022
  Leetcode-Medium/22-Generate Parentheses/generate_parentheses.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#151 Container with most water, a pr under hacktoberfest2022
  Leetcode-Medium/11-Container With Most Water/container-with-most-water.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#150 695 problem solved
  Leetcode-Medium/695-MaxAreaofIsland/max_area_of_Island.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#109 Added Codeforces folder for EDU and Problemset Solutions
  Codeforces/EDU/Binary Search_Step-1/A - Binary Search.py
  Codeforces/Problemset/test.txt
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#184 Rotate Image.cpp
  Leetcode-Medium/48 - Rotate Image/Rotate Image.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#180 Leetcode Easy 125,127,258,268 solution added
  Leetcode-Easy/121-Best Time to Buy and Sell Stock/Buy_&_Sell_Stock.py
  Leetcode-Easy/125-Valid Palindrome/Valid_Palindrome.py
  Leetcode-Easy/217-Contains Duplicate/Contains_Duplicate.py
  Leetcode-Easy/258.-Add Digits/Add_Digits.py
  Leetcode-Easy/268-Missing Numbe/Missing_Num.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#183 added solutions to the appropriate folders in Leetcode-Easy
  Leetcode-Easy/14-LongestCommonPrefix/14. Longest Common Prefix
  Leetcode-Easy/58-LengthOfLastWord/lastword.java
  Leetcode-Easy/9-PalindromeNumber/9-Palindrome.java
  Leetcode-Easy/9-PalindromeNumber/Palindrome.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#193 wrote the cpp approach of Two Sum ii - input array is sorted
  Leetcode-Medium/167-Two Sum II - Input Array Is Sorted/Solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#194 Maximum sybarray 53, and valid anagram solution added
  Leetcode-Easy/242. Valid Anagram/Valid Anagram.py
  Leetcode-Easy/53. Maximum Subarray/maxSubArr.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#186 Solution for letter-combinations-of-a-phone-number
  Leetcode-Medium/17-LetterCombinationsOfAPhoneNumber/solution.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#198 added cpp solution for Letter-Combination Leetcode.
  Leetcode-Medium/17-LetterCombinationsOfAPhoneNumber/solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#199 added cpp solution for maxSubarray leetcode question.
  Leetcode-Easy/53. Maximum Subarray/maxSubarray.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#203 Adding Python version of RomanToInteger solution
  Leetcode-Easy/13-RomanToInteger/roman_to_integer.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#204 Create Solution.cpp
  Leetcode-Easy/1672-Richest Customer Wealth/Solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#210 Added solution for 53. Maximum Subarray
  Leetcode-Medium/Maximum Subarray/53. Maximum Subarray.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#161 Added solution for Leetcode Medium 199. Binary Tree Right Side View
  Leetcode-Hard/188. Best Time to Buy and Sell Stock IV/solution.cpp
  Leetcode-Medium/199 - Binary Tree Right Side View/solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#215 maximum population year solution added in java
  Leetcode-Easy/Maximum population year/max_pop.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#241 [ISSUE 205] - 242. Valid Anagram in Java
  Leetcode-Easy/242. Valid Anagram/valid_anagram.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#261 Added solution
  Leetcode-Medium/946-validate-stack-sequences/solution.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#260 Added solution in python
  Leetcode-Hard/188. Best Time to Buy and Sell Stock IV/Best-Time-to-Buy-ad-Sell-Stock-IV.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#254 Maximum Subarray
  Leetcode-Easy/53. Maximum Subarray/Maximum Subarray(Java)
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
